apiVersion: v1
kind: Secret
metadata:
  name: {{ include "my-api.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "my-api.labels" . | nindent 4 }}

type: Opaque

stringData:
  DATABASE_USER: {{ .Values.secret.DATABASE_USER | quote }}
  DATABASE_PASSWORD: {{ .Values.secret.DATABASE_PASSWORD | quote }}