apiVersion: v1
kind: ResourceQuota
metadata:
  name: development-quota
  namespace: development
  labels:
    environment: development
    managed-by: platform-team
spec:
  hard:
    requests.cpu: "2" #The total CPU requests across workloads in this namespace cannot exceed:
    requests.memory: 4Gi #The total requested memory cannot exceed:
    limits.cpu: "4" #Total CPU limits cannot exceed:
    limits.memory: 8Gi #Total configured memory limits cannot exceed:
    pods: "20"
    services: "10"
    configmaps: "20"
    secrets: "10"