apiVersion: v2

name: my-api

description: Production-grade Node.js API for the platform demo

type: application

version: 0.1.0

appVersion: "1.0.0"

maintainers:
  - name: Viraj Solanki
    email: virajpsolanki404@email.com

keywords:
  - nodejs
  - api
  - platform-demo